spring.application.name=RAG-With-Spring-AI

# Ollama
spring.ai.ollama.base-url=http://localhost:11434

# Chat / LLM
spring.ai.ollama.chat.options.model=qwen3:1.7b

# Embeddings
spring.ai.ollama.embedding.options.model=nomic-embed-text