spring.application.name=RAG-With-Spring-AI

# Ollama
spring.ai.ollama.base-url=http://localhost:11434

# Chat / LLM
#spring.ai.ollama.chat.options.model=qwen3:4b
spring.ai.ollama.chat.options.model=llama3.2:3b

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
#spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

# Embeddings
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Elastic search
spring.elasticsearch.uris=http://localhost:9200
spring.ai.vectorstore.elasticsearch.initialize-schema=true
spring.ai.vectorstore.elasticsearch.dimensions=768

#enable this to know, internal tools calling
logging.level.org.springframework.ai=DEBUG
